sonar.projectKey=your-org_test-python-project
sonar.organization=your-org

sonar.projectName=test-python-project
sonar.projectVersion=0.1.0

sonar.sources=src/
sonar.tests=tests/
sonar.python.version=3.10

# Coverage
sonar.python.coverage.reportPaths=coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8
